### ISSUE TITLE
Improve requests error handling for OIDC auth

### ISSUE THREAD

**Issue by busykoala** [busykoala/fastapi-opa#21]
For now, the exceptions of the flow are handled quite reliable.

On the other hand, the requests (using the requests library) should be improved when it comes to error handling.
A failing request should immediately raise an OIDCAuth error and stop the authentication process in a cleaner way.
Additionally, the log output needs to be improved to show e.g. the request's route for easier debugging.

At the same time solving this issue the general logging concept should be overthought. Which logger is used, and what's the output channel?

**Comment by mleist** [comment]
Yes, when testing against docker containers, of course a "Failed to establish a new connection: [Errno 61] Connection refused" error also occurs.
The app container is much faster than OPA or keycloak test containers.
Is there already an idea how we want to tackle the problem? (Retries, timeouts, etc)

possible ideas I found (in a very quick search) here:
https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/

**Comment by busykoala** [comment]
Hi @mleist,
sorry for my late answer. I was thinking of better handling the errors in terms of wrapping the request into try/except and then raise very secific errors. Also I was thinking of a library wide logger configured in e.g. a ini file.
Using the mentioned hooks could be a nice abstraction especially to differ between log levels. I would not log the request exceptions directly though for security reasons, in case a potential attacker can somehow access the logs.
In your case we might need to make the timeout configurable. Can you give a minimal example of your setup so that I can reproduce the issue?
That said, I will not be able to spend a lot of time currently to improve the library but I'm more than happy to look at any proposals or PRs or spend some long nights to fix any requested things ;)

**Comment by busykoala** [comment]
I'll close this for now since the logging was improved a bit in the meanwhile and for the timeout issue mentioned there was no reproducible example provided. Feel free to open an issue again though and I'll try to look into it.
