### ISSUE TITLE
Support fastapi >= 0.66

### ISSUE THREAD

**Issue by samedii** [busykoala/fastapi-opa#34]
**Is your feature request related to a problem? Please describe.**
Would be comforting to know why later versions of fastapi do not work and if there's interest in supporting it. Otherwise it might feel safer to roll your own

**Describe the solution you'd like**
Support for later versions or open issue on why fastapi >= 0.66 does not work

**Describe alternatives you've considered**
I think this repo looks to have the nicest solution and I am comparing with `fastapi-oidc` and modifying an example.

**Comment by busykoala** [comment]
There is no specific reason for that and it can definitely be changed. I can look at it in a few days, or you can also open a PR.
