### ISSUE TITLE
OIDC redirect URL has wrong scheme when behind Ingress that terminates SSL

### ISSUE THREAD

**Issue by DiamondJoseph** [busykoala/fastapi-opa#68]
**Describe the bug**
In a Kubernetes environment, with the SSL connection terminated at the ingress and with a FastAPI app behind, `request.url.scheme` as retrieved by the OIDC authentication is `http`.
When using an OIDC client-id that is valid for "https://<path>", the OIDC provider does not allow the login to progress as the redirect uri does not match the Callback URL regex for the client-id.

I think the redirect uri could use the `x-forwarded-proto` header, if provided, in place of the request.uri.scheme, but I do not know enough about web routing to know if this is the correct solution.

**To Reproduce**
1. Configure a Kubernetes cluster with the Nginx Ingress Controller and SSL termination
2. Configure an OIDC provider with a client-id with a redirect regex of "https://<subdomain>.<domain>.<TLD>/*"
3. Deploy FastAPI with the fastapi-opa middleware and the oidc authentication method configured.
4. Access your https://<subdomain>.<domain>.<TLD>
5. Your OIDC provider will return a 401 at https://<OIDC_Provder>/<Authorize Endpoint>?response_type=code&scope=openid&client_id=<your client id>&redirect_uri=http://<subdomain>.<domain>.<TLD>

**Expected behavior**
5. Your OIDC provider serves its login page at at https://<OIDC_Provder>/<Authorize Endpoint>?response_type=code&scope=openid&client_id=<your client id>&redirect_uri=https://<subdomain>.<domain>.<TLD>

**Comment by busykoala** [comment]
Thanks for raising the issue. I'm currently super busy and would need to devote some work to reproduce the issue. I'll either look into it a bit later or you can also PR incl. some easily understandable tests proving that this situation is handled correctly.
I hope to be able to follow up as quick as possible though.
